trigger: none  # or specify your trigger

variables:
  sourceSubscription: '<source-subscription-id>'
  descriptionSubscription: '<destination-subscription-id>'
  sourceVaultName: '<source-keyvault-name>'
  destVaultName: '<destination-keyvault-name>'

stages:
  - stage: CopySecrets
    jobs:
      - job: CopySecretsJob
        displayName: 'Copy secrets between Key Vaults'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            name: CopySecrets
            inputs:
              azureSubscription: '<your-service-connection-name>' # Replace with your Azure service connection name
              scriptType: 'pscore'  # PowerShell Core (cross-platform)
              scriptLocation: 'inlineScript'
              inlineScript: |
                $ErrorActionPreference = "Stop"

                $sourceSubscription = '$(sourceSubscription)'
                $descriptionSubscription = '$(descriptionSubscription)'
                $sourceVaultName = '$(sourceVaultName)'
                $destVaultName = '$(destVaultName)'

                if ($sourceSubscription) {
                    az account set --subscription $sourceSubscription
                }

                Write-Host "Reading secret names from $sourceVaultName"
                $secretNames = az keyvault secret list --vault-name $sourceVaultName -o json --query "[].name" | ConvertFrom-Json

                Write-Host "Reading secret values"
                $secrets = foreach ($name in $secretNames) {
                    $secret = az keyvault secret show --name $name --vault-name $sourceVaultName -o json | ConvertFrom-Json
                    [PSCustomObject]@{
                        name  = $name
                        value = $secret.value
                    }
                }

                Write-Host "Writing secrets to $destVaultName"
                if ($descriptionSubscription) {
                    az account set --subscription $descriptionSubscription
                }

                foreach ($s in $secrets) {
                    az keyvault secret set --vault-name $destVaultName --name $s.name --value $s.value
                }

            displayName: 'Copy Key Vault Secrets (Linux Agent)'












#######################################################################


#!/bin/bash
 
SOURCE_KEYVAULT="keyvaultold"
DESTINATION_KEYVAULT="keyvaultnewtest"
 
SECRETS+=($(az keyvault secret list --vault-name $SOURCE_KEYVAULT --query "[].id" -o tsv))
 
for SECRET in "${SECRETS[@]}"; do
 
SECRETNAME=$(echo "$SECRET" | sed 's|.*/||')
 
SECRET_CHECK=$(az keyvault secret list --vault-name $DESTINATION_KEYVAULT --query "[?name=='$SECRETNAME']" -o tsv)
 
 
if [ -n "$SECRET_CHECK" ]
then
    echo "A secret with name $SECRETNAME already exists in $DESTINATION_KEYVAULT"
else
    echo "Copying $SECRETNAME to KeyVault: $DESTINATION_KEYVAULT"
    SECRET=$(az keyvault secret show --vault-name $SOURCE_KEYVAULT -n $SECRETNAME --query "value" -o tsv)
    az keyvault secret set --vault-name $DESTINATION_KEYVAULT -n $SECRETNAME --value "$SECRET" >/dev/null
fi
 
done
